// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartPark.Data;

#nullable disable

namespace SmartPark.Data.Migrations
{
    [DbContext(typeof(SmartParkDbContext))]
    partial class SmartParkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartPark.Data.Entities.ParkingLot", b =>
                {
                    b.Property<int>("ParkingLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParkingLotId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParkingLotId");

                    b.ToTable("ParkingLots");

                    b.HasData(
                        new
                        {
                            ParkingLotId = 1,
                            Address = "IPCA",
                            Capacity = 50,
                            Name = "Campus - Parque A"
                        });
                });

            modelBuilder.Entity("SmartPark.Data.Entities.Spot", b =>
                {
                    b.Property<int>("SpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpotId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpotId");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("Spots");

                    b.HasData(
                        new
                        {
                            SpotId = 1,
                            Code = "A-01",
                            ParkingLotId = 1,
                            Status = "free"
                        },
                        new
                        {
                            SpotId = 2,
                            Code = "A-02",
                            ParkingLotId = 1,
                            Status = "occupied"
                        });
                });

            modelBuilder.Entity("SmartPark.Data.Entities.Spot", b =>
                {
                    b.HasOne("SmartPark.Data.Entities.ParkingLot", "ParkingLot")
                        .WithMany("Spots")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("SmartPark.Data.Entities.ParkingLot", b =>
                {
                    b.Navigation("Spots");
                });
#pragma warning restore 612, 618
        }
    }
}
